local Items = {
		["Skibidi_Toilet"] = {
			DisplayName = "Skibidi Toilet",
			Rarity = "Common",
			ImageId = "rbxassetid://95934746711773", -- Replace with decal ID
		},
		["Ohio_Rizz"] = {
			DisplayName = "Ohio Rizz",
			Rarity = "Common",
			ImageId = "rbxassetid://95753777543642",
		},
		["PLACEHOLDER1"] = {
			DisplayName = "PLACEHOLDER",
			Rarity = "Uncommon",
			ImageId = "rbxassetid://87747014552943",
		},
		["Grimace_Shake"] = {
			DisplayName = "Grimace Shake",
			Rarity = "Rare",
			ImageId = "rbxassetid://126144918462510",
		},
		["PLACEHOLDER2"] = {
			DisplayName = "PLACEHOLDER2",
			Rarity = "Epic",
			ImageId = "rbxassetid://117563080173051",
		},
		["Capybara"] = {
			DisplayName = "Capybara",
			Rarity = "Legendary",
			ImageId = "rbxassetid://130451135016933",
		},
		["Yes"] = {
			DisplayName = "Yes",
			Rarity = "Mythical",
			ImageId = "rbxassetid://125238880495947",
		},
		["PLACEHOLDER3"] = {
			DisplayName = "PLACEHOLDER3",
			Rarity = "Cosmic",
			ImageId = "rbxassetid://97950504020289",
		},
}

return Items